

version: "3.8"

services:
  mysql-db:
    build:
      context: ./mysql-server
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: librarydb
    ports:
      - "3306:3306"

  library-backend:
    build:
      context: ./backend
    container_name: library-backend
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/librarydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
