dockerComposeFilePath: ./docker-compose.yml

services:
  - type: web
    name: library-app
    env: docker
    repo: https://github.com/Himmu9131/student-library-management-system
    
    plan: free
    region: oregon
    branch: main
    autoDeploy: true
